GET http://localhost:8080/ticket/list/Pending
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjMDYyMGcxQGdtYWlsLmNvbSIsImV4cCI6MTYwODE0MjcwMSwiaWF0IjoxNjA4MTI0NzAxfQ.9G0rcbnSb4ljSsKz4K-mpnmLc_TOnDdbb2TNrWgbNTKN7P1rD9rqBLnqd6CbjxK4ZES9Yuh-2X8CuSTjxMuTzw

###
GET http://localhost:8080/ticket/findTicketByID/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjMDYyMGcxQGdtYWlsLmNvbSIsImV4cCI6MTYwODE0MjcwMSwiaWF0IjoxNjA4MTI0NzAxfQ.9G0rcbnSb4ljSsKz4K-mpnmLc_TOnDdbb2TNrWgbNTKN7P1rD9rqBLnqd6CbjxK4ZES9Yuh-2X8CuSTjxMuTzw

###
GET http://localhost:8080/ticket/search?statusPaymentName=Pending&searchBy=bookingCode&searchValue=123
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjMDYyMGcxQGdtYWlsLmNvbSIsImV4cCI6MTYwODE4NjY5MSwiaWF0IjoxNjA4MTY4NjkxfQ.3VNlkQ0bQQ7qrIngFSlHqbkjOaH-ADo1B5Y3N2tFOoE_zx0geG-GfqGNdDl2GF_BdyWvGvqMvYEva4M4QaozSw

###



